Custom serializers and deserializers for types can be written by implementing the api:serde.Serializer[] and api:serde.Deserializer[] interfaces respectively and defining beans capable of handling a particular type.

For example given the following class:

snippet::example.Point[source="main"]

A custom serde (a combined serializer and deserializer) can be implemented as follows:

snippet::example.PointSerde[source="main"]

<1> The api:serde.Serde[] is made a bean by annotating it with `@Singleton` scope.
<2> The api:serde.Serde[] interface is implemented for a given type.
<3> The api:serde.Decoder[] interface is used to starting decoding an array using `try-with-resources`
<4> The decoded object is returned
<5> The `value` can be `null` and the decoder should handle whether `null` is allowed
<6> The api:serde.Encoder[] interface is used to start encoding an array with the `encodeArray` method using `try-with-resources`.

You can now serialize and deserialize classes of type `Point`:

snippet::example.PointTest[]

=== Serializer Selection

Note that if multiple api:serde.Serializer[] beans exist you will get a `NonUniqueBeanException`, in this case you have a number of options:

1. Add `@Primary` to your serializer so it is picked
2. Add `@Order` with a higher priority value so it is picked

=== Deserializer Selection

It is quite common during deserialization to have multiple possible deserializer options. For example a `HashSet` can be deserialized to both a `Collection` and a `Set`.

In these cases you should declare an `@Order` annotation higher priority value to control which deserializer is chosen by default.

=== Property Level Serializer or Deserializer

You can also customize the serializer and/or deserializer on a per field, constructor, method etc. basis by using the `@Serializable(using=..)` and/or `@Deserializable(using=..)` annotations.

NOTE: Frequently in this case you will more than one serializer/deserializer for a given type and you should use `@Primary` or `@Secondary` to customize bean property so one is selected by default.

For example say you add another secondary `Serde` to store the previous `Point` example in reverse order:

snippet::example.ReversePointSerde[source="main"]

<1> This bean is made `@Secondary` so the primary `Serde` serializes by default in the correct order
<2> The coordinates are stored in reverse order

You can then define annotations at field, parameter, method etc. level to customize serialization/deserialization for just that case:

snippet::example.Place[source="main"]

<1> `@Serializable(using=..)` indicates to use the `ReversePointSerde` to serialize the coordinates
<2> `@Serializable(using=..)` indicates to use the `ReversePointSerde` to deserialize the coordinates

