repositories {
    mavenCentral()
}

configurations.configureEach {
    resolutionStrategy {
        preferProjectModules()
        eachDependency {
            if (requested.group == "io.micronaut.sourcegen") {
                useVersion(libs.versions.micronaut.sourcegen.get())
                because("Micronaut Serialization requires a newer SourceGen version than the imported Micronaut Core BOM")
            }
        }
    }
}
