plugins {
    id("io.micronaut.build.internal.serde-base")
    id("io.micronaut.minimal.application")
}

micronaut {
    version libs.versions.micronaut.platform.get()
}

dependencies {
    // Gradle 9 requires explicitly adding the JUnit Platform Launcher on the test runtime classpath
    testRuntimeOnly(libs.junit.platform.launcher)
}
