/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.serde.support.serdes;

import io.micronaut.context.annotation.Requires;
import io.micronaut.context.annotation.Secondary;
import io.micronaut.core.annotation.Internal;
import io.micronaut.core.type.Argument;
import io.micronaut.core.value.OptionalMultiValues;
import io.micronaut.http.hateoas.GenericResource;
import io.micronaut.http.hateoas.Link;
import io.micronaut.http.hateoas.Resource;
import io.micronaut.serde.Decoder;
import io.micronaut.serde.Deserializer;
import io.micronaut.serde.Encoder;
import io.micronaut.serde.Serde;
import io.micronaut.serde.Serializer;
import jakarta.inject.Singleton;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * Serde for {@link GenericResource}. The introspection of {@link GenericResource} is generated by
 * micronaut-http without the serde annotation processor, so its {@code @JsonAnyGetter} and
 * {@code @JsonAnySetter} are not applied: this serde writes the additional properties next to
 * {@code _links} and {@code _embedded}, as jackson-databind does, and reads unknown properties back
 * as additional properties.
 *
 * @since 3.2.1
 */
@Internal
@Singleton
@Secondary
@Requires(classes = GenericResource.class)
public final class GenericResourceSerde implements Serde<GenericResource> {

    @SuppressWarnings({"unchecked", "rawtypes"})
    private static final Argument<OptionalMultiValues<Link>> LINKS_TYPE = (Argument) Argument.of(OptionalMultiValues.class, Link.class);
    @SuppressWarnings({"unchecked", "rawtypes"})
    private static final Argument<OptionalMultiValues<Resource>> EMBEDDED_TYPE = (Argument) Argument.of(OptionalMultiValues.class, Resource.class);
    private static final Argument<Map<String, List<Resource>>> EMBEDDED_MAP_TYPE = Argument.mapOf(Argument.STRING, Argument.listOf(Resource.class));

    @Override
    public void serialize(Encoder encoder, EncoderContext context, Argument<? extends GenericResource> type, GenericResource value) throws IOException {
        Encoder object = encoder.encodeObject(type);
        Map<String, Object> additionalProperties = value.getAdditionalProperties();
        if (!additionalProperties.isEmpty()) {
            Serializer<? super Object> valueSerializer = context.findSerializer(Argument.OBJECT_ARGUMENT)
                .createSpecific(context, Argument.OBJECT_ARGUMENT);
            for (Map.Entry<String, Object> entry : additionalProperties.entrySet()) {
                object.encodeKey(entry.getKey());
                Object propertyValue = entry.getValue();
                if (propertyValue == null) {
                    object.encodeNull();
                } else {
                    valueSerializer.serialize(object, context, Argument.OBJECT_ARGUMENT, propertyValue);
                }
            }
        }
        OptionalMultiValues<Link> links = value.getLinks();
        if (!links.isEmpty()) {
            object.encodeKey(Resource.LINKS);
            context.findSerializer(LINKS_TYPE).createSpecific(context, LINKS_TYPE).serialize(object, context, LINKS_TYPE, links);
        }
        OptionalMultiValues<Resource> embedded = value.getEmbedded();
        if (!embedded.isEmpty()) {
            object.encodeKey(Resource.EMBEDDED);
            context.findSerializer(EMBEDDED_TYPE).createSpecific(context, EMBEDDED_TYPE).serialize(object, context, EMBEDDED_TYPE, embedded);
        }
        object.finishStructure();
    }

    @SuppressWarnings({"unchecked", "NullAway"}) // a null property value is kept, as with jackson-databind
    @Override
    public GenericResource deserialize(Decoder decoder, DecoderContext context, Argument<? super GenericResource> type) throws IOException {
        GenericResource resource = new GenericResource();
        Decoder object = decoder.decodeObject(type);
        String key;
        while ((key = object.decodeKey()) != null) {
            switch (key) {
                case Resource.LINKS -> {
                    Object links = object.decodeArbitrary();
                    if (links instanceof Map<?, ?> linksMap) {
                        resource.setLinks((Map<String, Object>) linksMap);
                    } else if (links != null) {
                        throw object.createDeserializationException("Expected an object for " + Resource.LINKS, links);
                    }
                }
                case Resource.EMBEDDED -> {
                    // resolved here, not in createSpecific: the embedded resources are read by this serde again
                    Deserializer<? extends Map<String, List<Resource>>> embeddedDeserializer = context.findDeserializer(EMBEDDED_MAP_TYPE)
                        .createSpecific(context, EMBEDDED_MAP_TYPE);
                    Map<String, List<Resource>> embedded = embeddedDeserializer.deserializeNullable(object, context, EMBEDDED_MAP_TYPE);
                    if (embedded != null) {
                        resource.setEmbedded(embedded);
                    }
                }
                default -> resource.addProperty(key, object.decodeArbitrary());
            }
        }
        object.finishStructure();
        return resource;
    }
}
