[versions]
managed-bson = "4.11.5"
managed-jakarta-json-api = "2.1.3"
managed-jakarta-json-bindApi = "3.0.1"
managed-eclipse-parsson = "1.1.7"

graal-svm = "23.1.10"
aws-lambda-events = "3.16.1"
aws-lambda-serialization = "1.2.0"
microstream-storage-restclient = "08.01.02-MS-GA"
oracle-jdbc-driver = "23.26.1.0.0"
jetbrains-annotations = "24.1.0"
jmh = "1.37"
lombok = "1.18.42"

micronaut-platform = "4.10.7"
micronaut = "5.0.0-M9"
micronaut-discovery = "4.7.2"
micronaut-logging = "1.7.1"
micronaut-oracle-cloud = "5.6.1"
micronaut-reactor = "3.9.1"
micronaut-validation = "4.12.0"
micronaut-gradle-plugin = "4.6.1"
jsonassert = "1.5.3"

[libraries]
# Micronaut
micronaut-core = { module = "io.micronaut:micronaut-core-bom", version.ref = "micronaut" }
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut-platform"}
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }
micronaut-oracle-cloud = { module = 'io.micronaut.oraclecloud:micronaut-oraclecloud-bom', version.ref = 'micronaut-oracle-cloud' }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-discovery = { module = "io.micronaut.discovery:micronaut-discovery-client", version.ref = "micronaut-discovery" }

managed-bson = { module = "org.mongodb:bson", version.ref = "managed-bson" }
managed-eclipse-parsson = { module = "org.eclipse.parsson:parsson", version.ref = "managed-eclipse-parsson" }
managed-jakarta-json-api = { module = "jakarta.json:jakarta.json-api", version.ref = "managed-jakarta-json-api" }
managed-jakarta-json-bindApi = { module = "jakarta.json.bind:jakarta.json.bind-api", version.ref = "managed-jakarta-json-bindApi" }

oracle-jdbc-driver = { module = "com.oracle.database.jdbc:ojdbc8", version.ref = "oracle-jdbc-driver" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
aws-lambda-events = { module = "com.amazonaws:aws-lambda-java-events", version.ref = "aws-lambda-events" }
aws-lambda-serialization = { module = "com.amazonaws:aws-lambda-java-serialization", version.ref = "aws-lambda-serialization" }
graal-svm = { module = "org.graalvm.sdk:nativeimage", version.ref = "graal-svm" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

microstream-storage-restclient = { module = "one.microstream:microstream-storage-restclient", version.ref = "microstream-storage-restclient" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-suite-engine" }

jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

oci-aidocument = { module = "com.oracle.oci.sdk:oci-java-sdk-aidocument" }
jsonassert = { module = 'org.skyscreamer:jsonassert', version.ref = 'jsonassert'}

#PLUGINS
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
