To completely remove all dependencies on Jackson and use JSON-B annotations in your source code combined with JSON-P at a runtime you should exclude the `micronaut-jackson-databind` and `micronaut-jackson-core` modules from your application and replace them with `micronaut-serde-jsonp`.

To do so in a Gradle build add the following configuration (either Groovy or Kotlin):

[source,groovy,subs="attributes+"]
----
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("io.micronaut:micronaut-jackson-databind"))
            .using(module("jakarta.json.bind:jakarta.json.bind-api:2.0.0"))
        substitute(module("io.micronaut:micronaut-jackson-core"))
            .using(module("io.micronaut.serde:micronaut-serde-jsonp:{version}"))
    }
}
----

In a Maven build you need to add the necessary transitive excludes for the `micronaut-runtime` module, and any other module that depend on `micronaut-jackson-databind` and `micronaut-jackson-core`, plus add a dependency on `micronaut-serde-jackson`:

[source,xml,subs="attributes+"]
----
 <dependency>
  <groupId>io.micronaut</groupId>
  <artifactId>micronaut-runtime</artifactId>
  <exclusions>
    <exclusion>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-jackson-databind</artifactId>
    </exclusion>
  </exclusions>
  <scope>compile</scope>
</dependency>
<dependency>
  <groupId>io.micronaut.serde</groupId>
  <artifactId>micronaut-serde-jsonp</artifactId>
  <version>{version}</version>
  <scope>compile</scope>
</dependency>
<dependency>
  <groupId>jakarta.json.bind</groupId>
  <artifactId>jakarta.json.bind-api</artifactId>
  <version>2.0.0</version>
  <scope>compile</scope>
</dependency>
----


With the correct dependencies in place you can now define an object to be serialized:

snippet::example.Book[project-base="doc-examples/example-jsonb", source="main"]

<1> The type is annotated with ann:serde.annotation.Serdeable[] to enable serialization/deserialization
<2> You can use `@JsonbProperty` from JSON-B annotations
<3> You can use `@JsonbCreator` from JSON-B annotations

Once you have a type that can be serialized and deserialized you can use the api:serde.ObjectMapper[] interface to do so:

snippet::example.BookTest[project-base="doc-examples/example"]