/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.27
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.micronaut.serde.jackson.generic.scenario1;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;
import io.micronaut.serde.annotation.Serdeable;

/**
 * Namespace provides a scope for Names. Use of multiple namespaces is optional.
 */
@Serdeable
public class V1Namespace {

    public static final String JSON_PROPERTY_API_VERSION = "apiVersion";

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_API_VERSION)
    @JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    private String apiVersion;


    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     *
     * @return the apiVersion property value
     */
    public String getApiVersion() {
        return apiVersion;
    }

    /**
     * Set the apiVersion property value
     *
     * @param apiVersion property value to set
     */
    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
    }

    /**
     * Set apiVersion in a chainable fashion.
     *
     * @return The same instance of V1Namespace for chaining.
     */
    public V1Namespace apiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }


}
