package example.openapi.test.model

import com.fasterxml.jackson.annotation.*
import org.jspecify.annotations.Nullable
import io.micronaut.serde.annotation.Serdeable
import jakarta.annotation.Generated
import java.util.*

/**
 * Animal
 */
@Serdeable
@JsonPropertyOrder(
    Animal.JSON_PROPERTY_PROPERTY_CLASS,
    Animal.JSON_PROPERTY_COLOR,
)
@Generated("io.micronaut.openapi.generator.KotlinMicronautServerCodegen")
@JsonIgnoreProperties(
    value = ["class"], // ignore manually set class, it will be automatically generated by Jackson during serialization
    allowSetters = true, // allows the class to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "class", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = Bird::class, name = "ave"),
    JsonSubTypes.Type(value = Mammal::class, name = "mammalia"),
    JsonSubTypes.Type(value = Reptile::class, name = "reptilia"),
)
open class Animal(

    @field:Nullable
    @field:JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
    @field:JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    open var propertyClass: String? = null,

    @field:Nullable
    @field:JsonProperty(JSON_PROPERTY_COLOR)
    @field:JsonInclude(JsonInclude.Include.USE_DEFAULTS)
    open var color: ColorEnum? = null,
) {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        if (javaClass != other?.javaClass) {
            return false
        }
        other as Animal
        return propertyClass == other.propertyClass
                && color == other.color
    }

    override fun hashCode(): Int =
        Objects.hash(propertyClass, color)

    override fun toString(): String =
        "Animal(propertyClass='$propertyClass', color='$color')"

    companion object {

        const val JSON_PROPERTY_PROPERTY_CLASS = "class"
        const val JSON_PROPERTY_COLOR = "color"
    }
}
